### ISSUE TITLE
统计数量出现错误

### ISSUE THREAD

**Issue by lwhzbyz** [sinyang92/gbf-BlueChestCounter#10]
最近碰上了奇怪的统计错误，群里也有其他朋友遇到，蓝箱的数量会莫名其妙的变多，多出很多红戒指或者ffj的数据，请问这个可以怎么解决呢？

或者有没有什么办法手动编辑修改掉错误的数据也可以，非常感谢！
![image](https://user-images.githubusercontent.com/33936885/224863024-9f7f5d91-0674-42d8-86a2-1875ffb012d1.png)
（应该是22金，出了第22金后又打了一小会没有出金，就变成了67金）

**Comment by sinyang92** [comment]
8号更新了一下，试过了没？
如果还是有问题，麻烦具体描述一下场景，以及
- 有没有双窗
- 有没有用书签跳转页面（结算->选召唤，结算->结算，之类）
- akx大公有没有这个问题
- 每次结算都乱跳，还是偶尔几只

**Comment by lwhzbyz** [comment]
没有注意到有更新，那我更新一下再看一下吧

十分感谢！

**Comment by sinyang92** [comment]
如果还有问题请重新提issue
