### ISSUE TITLE
如何获得掉落物的“data-key”?

### ISSUE THREAD

**Issue by OoVToO** [sinyang92/gbf-BlueChestCounter#11]
我正在学习您的代码，来制作自动统计沙漏掉落，但是因为没掉过沙漏，无法获得沙漏的data-key，请问有什么其他办法可以获取data-key吗？

**Comment by sinyang92** [comment]
应该是10_215。星晶兽材料是10开头，沙漏看图片编号是215号：
https://prd-game-a-granbluefantasy.akamaized.net/assets/img/sp/assets/item/article/m/215.jpg

**Comment by OoVToO** [comment]
好的，多谢大佬
