### ISSUE TITLE
[建議] 統計大巴數量的方法

### ISSUE THREAD

**Issue by TsungLinYeh** [sinyang92/gbf-BlueChestCounter#3]
如果 wiki 資料正確,巴角以及紫電角那箱也是必掉
![CleanShot 2022-02-05 at 16 54 48](https://user-images.githubusercontent.com/61908909/152635302-64ca030e-f17c-4594-8c74-f95eccf76a16.jpg)

紫電角只有大巴會掉,而巴角只有大巴以及小巴會掉
![CleanShot 2022-02-05 at 16 56 22](https://user-images.githubusercontent.com/61908909/152635405-a7943cb1-c67e-438b-9999-87b761327c57.jpg)

可以藉由小巴固定掉落至少一把朽武排除誤算小巴的情形

**Comment by sinyang92** [comment]
朽武的问题在于要把十把的ID全写进判断，太麻烦了。而且这个跟现在判断 （真球 AND 蓝箱是戒指FFJ） 的时间差不多的。目前应该没有什么能污染数据的本，方阵2.0蓝箱不掉戒指，而六龙不掉真球，所以数据是准确的。

**Comment by TsungLinYeh** [comment]
主要就是想計算大巴藍箱率
大巴獵金的時候還是蠻在意這個數據

剛剛看了一下不同數量紫電角的物品 id 是相同的
大約九成的情況都會被紫電角這個判定攔下來, 剩下一成再檢查有無朽武就可以了
即使不統計沒藍箱的情形也可以考慮將目前的檢查六屬真球改成檢查巴角跟紫電角
因為小巴沒有藍箱,不會有汙染數據的問題

**Comment by sinyang92** [comment]
我创建了1.0.4.1的branch，如果想可以把你统计大巴只数的code合过去
